//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interface.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BloodDonator", Namespace="http://schemas.datacontract.org/2004/07/Socorro")]
    [System.SerializableAttribute()]
    public partial class BloodDonator : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirthDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BloodTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CentimetersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ImcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double KilogramsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MothersMaidenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OccupationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatefullField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TelephoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthDay {
            get {
                return this.BirthDayField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthDayField, value) != true)) {
                    this.BirthDayField = value;
                    this.RaisePropertyChanged("BirthDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BloodType {
            get {
                return this.BloodTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.BloodTypeField, value) != true)) {
                    this.BloodTypeField = value;
                    this.RaisePropertyChanged("BloodType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Centimeters {
            get {
                return this.CentimetersField;
            }
            set {
                if ((this.CentimetersField.Equals(value) != true)) {
                    this.CentimetersField = value;
                    this.RaisePropertyChanged("Centimeters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guid {
            get {
                return this.GuidField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidField, value) != true)) {
                    this.GuidField = value;
                    this.RaisePropertyChanged("Guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Imc {
            get {
                return this.ImcField;
            }
            set {
                if ((this.ImcField.Equals(value) != true)) {
                    this.ImcField = value;
                    this.RaisePropertyChanged("Imc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Kilograms {
            get {
                return this.KilogramsField;
            }
            set {
                if ((this.KilogramsField.Equals(value) != true)) {
                    this.KilogramsField = value;
                    this.RaisePropertyChanged("Kilograms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MothersMaiden {
            get {
                return this.MothersMaidenField;
            }
            set {
                if ((object.ReferenceEquals(this.MothersMaidenField, value) != true)) {
                    this.MothersMaidenField = value;
                    this.RaisePropertyChanged("MothersMaiden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Occupation {
            get {
                return this.OccupationField;
            }
            set {
                if ((object.ReferenceEquals(this.OccupationField, value) != true)) {
                    this.OccupationField = value;
                    this.RaisePropertyChanged("Occupation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Statefull {
            get {
                return this.StatefullField;
            }
            set {
                if ((object.ReferenceEquals(this.StatefullField, value) != true)) {
                    this.StatefullField = value;
                    this.RaisePropertyChanged("Statefull");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetAddress {
            get {
                return this.StreetAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetAddressField, value) != true)) {
                    this.StreetAddressField = value;
                    this.RaisePropertyChanged("StreetAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TelephoneNumber {
            get {
                return this.TelephoneNumberField;
            }
            set {
                if ((this.TelephoneNumberField.Equals(value) != true)) {
                    this.TelephoneNumberField = value;
                    this.RaisePropertyChanged("TelephoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vehicle {
            get {
                return this.VehicleField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleField, value) != true)) {
                    this.VehicleField = value;
                    this.RaisePropertyChanged("Vehicle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecureString", Namespace="http://schemas.datacontract.org/2004/07/System.Security")]
    [System.SerializableAttribute()]
    public partial class SecureString : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NetworkCredential", Namespace="http://schemas.datacontract.org/2004/07/System.Net")]
    [System.SerializableAttribute()]
    public partial class NetworkCredential : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DomainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Interface.ServiceReference1.SecureString SecurePasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Domain {
            get {
                return this.DomainField;
            }
            set {
                if ((object.ReferenceEquals(this.DomainField, value) != true)) {
                    this.DomainField = value;
                    this.RaisePropertyChanged("Domain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Interface.ServiceReference1.SecureString SecurePassword {
            get {
                return this.SecurePasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurePasswordField, value) != true)) {
                    this.SecurePasswordField = value;
                    this.RaisePropertyChanged("SecurePassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Devolver", ReplyAction="http://tempuri.org/IService1/DevolverResponse")]
        bool Devolver(string textotxt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Devolver", ReplyAction="http://tempuri.org/IService1/DevolverResponse")]
        System.Threading.Tasks.Task<bool> DevolverAsync(string textotxt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNewDonator", ReplyAction="http://tempuri.org/IService1/AddNewDonatorResponse")]
        bool AddNewDonator(Interface.ServiceReference1.BloodDonator bd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNewDonator", ReplyAction="http://tempuri.org/IService1/AddNewDonatorResponse")]
        System.Threading.Tasks.Task<bool> AddNewDonatorAsync(Interface.ServiceReference1.BloodDonator bd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DevolverXml", ReplyAction="http://tempuri.org/IService1/DevolverXmlResponse")]
        System.Xml.XmlElement DevolverXml();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DevolverXml", ReplyAction="http://tempuri.org/IService1/DevolverXmlResponse")]
        System.Threading.Tasks.Task<System.Xml.XmlElement> DevolverXmlAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoverDonator", ReplyAction="http://tempuri.org/IService1/RemoverDonatorResponse")]
        bool RemoverDonator(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoverDonator", ReplyAction="http://tempuri.org/IService1/RemoverDonatorResponse")]
        System.Threading.Tasks.Task<bool> RemoverDonatorAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListDonators", ReplyAction="http://tempuri.org/IService1/ListDonatorsResponse")]
        Interface.ServiceReference1.BloodDonator[] ListDonators();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListDonators", ReplyAction="http://tempuri.org/IService1/ListDonatorsResponse")]
        System.Threading.Tasks.Task<Interface.ServiceReference1.BloodDonator[]> ListDonatorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalcularIMC", ReplyAction="http://tempuri.org/IService1/CalcularIMCResponse")]
        double CalcularIMC(double peso, double altura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalcularIMC", ReplyAction="http://tempuri.org/IService1/CalcularIMCResponse")]
        System.Threading.Tasks.Task<double> CalcularIMCAsync(double peso, double altura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaDonators", ReplyAction="http://tempuri.org/IService1/ListaDonatorsResponse")]
        Interface.ServiceReference1.BloodDonator[] ListaDonators();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaDonators", ReplyAction="http://tempuri.org/IService1/ListaDonatorsResponse")]
        System.Threading.Tasks.Task<Interface.ServiceReference1.BloodDonator[]> ListaDonatorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDonator", ReplyAction="http://tempuri.org/IService1/AddDonatorResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Interface.ServiceReference1.SecureString))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Interface.ServiceReference1.NetworkCredential))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Interface.ServiceReference1.BloodDonator))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Interface.ServiceReference1.BloodDonator[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        System.Xml.XmlElement AddDonator(
                    string number, 
                    string sexo, 
                    string firstName, 
                    string lastName, 
                    string streetAddress, 
                    string city, 
                    string statefull, 
                    string zipCode, 
                    string eMail, 
                    string userName, 
                    string password, 
                    string telephoneNumber, 
                    string mothersMaiden, 
                    string birthDay, 
                    string age, 
                    string occupation, 
                    string company, 
                    string vehicle, 
                    string bloodType, 
                    string kilograms, 
                    string centimeters, 
                    string guid, 
                    string latitude, 
                    string longitude, 
                    object[] doc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDonator", ReplyAction="http://tempuri.org/IService1/AddDonatorResponse")]
        System.Threading.Tasks.Task<System.Xml.XmlElement> AddDonatorAsync(
                    string number, 
                    string sexo, 
                    string firstName, 
                    string lastName, 
                    string streetAddress, 
                    string city, 
                    string statefull, 
                    string zipCode, 
                    string eMail, 
                    string userName, 
                    string password, 
                    string telephoneNumber, 
                    string mothersMaiden, 
                    string birthDay, 
                    string age, 
                    string occupation, 
                    string company, 
                    string vehicle, 
                    string bloodType, 
                    string kilograms, 
                    string centimeters, 
                    string guid, 
                    string latitude, 
                    string longitude, 
                    object[] doc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExportarXML", ReplyAction="http://tempuri.org/IService1/ExportarXMLResponse")]
        bool ExportarXML(int[] posicao, string caminhoGuardar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExportarXML", ReplyAction="http://tempuri.org/IService1/ExportarXMLResponse")]
        System.Threading.Tasks.Task<bool> ExportarXMLAsync(int[] posicao, string caminhoGuardar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExportJSON", ReplyAction="http://tempuri.org/IService1/ExportJSONResponse")]
        bool ExportJSON(int[] posicao, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExportJSON", ReplyAction="http://tempuri.org/IService1/ExportJSONResponse")]
        System.Threading.Tasks.Task<bool> ExportJSONAsync(int[] posicao, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendEmails", ReplyAction="http://tempuri.org/IService1/SendEmailsResponse")]
        void SendEmails(string email, string bloodtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendEmails", ReplyAction="http://tempuri.org/IService1/SendEmailsResponse")]
        System.Threading.Tasks.Task SendEmailsAsync(string email, string bloodtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Credentials", ReplyAction="http://tempuri.org/IService1/CredentialsResponse")]
        Interface.ServiceReference1.NetworkCredential Credentials();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Credentials", ReplyAction="http://tempuri.org/IService1/CredentialsResponse")]
        System.Threading.Tasks.Task<Interface.ServiceReference1.NetworkCredential> CredentialsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Interface.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Interface.ServiceReference1.IService1>, Interface.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Devolver(string textotxt) {
            return base.Channel.Devolver(textotxt);
        }
        
        public System.Threading.Tasks.Task<bool> DevolverAsync(string textotxt) {
            return base.Channel.DevolverAsync(textotxt);
        }
        
        public bool AddNewDonator(Interface.ServiceReference1.BloodDonator bd) {
            return base.Channel.AddNewDonator(bd);
        }
        
        public System.Threading.Tasks.Task<bool> AddNewDonatorAsync(Interface.ServiceReference1.BloodDonator bd) {
            return base.Channel.AddNewDonatorAsync(bd);
        }
        
        public System.Xml.XmlElement DevolverXml() {
            return base.Channel.DevolverXml();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlElement> DevolverXmlAsync() {
            return base.Channel.DevolverXmlAsync();
        }
        
        public bool RemoverDonator(int id) {
            return base.Channel.RemoverDonator(id);
        }
        
        public System.Threading.Tasks.Task<bool> RemoverDonatorAsync(int id) {
            return base.Channel.RemoverDonatorAsync(id);
        }
        
        public Interface.ServiceReference1.BloodDonator[] ListDonators() {
            return base.Channel.ListDonators();
        }
        
        public System.Threading.Tasks.Task<Interface.ServiceReference1.BloodDonator[]> ListDonatorsAsync() {
            return base.Channel.ListDonatorsAsync();
        }
        
        public double CalcularIMC(double peso, double altura) {
            return base.Channel.CalcularIMC(peso, altura);
        }
        
        public System.Threading.Tasks.Task<double> CalcularIMCAsync(double peso, double altura) {
            return base.Channel.CalcularIMCAsync(peso, altura);
        }
        
        public Interface.ServiceReference1.BloodDonator[] ListaDonators() {
            return base.Channel.ListaDonators();
        }
        
        public System.Threading.Tasks.Task<Interface.ServiceReference1.BloodDonator[]> ListaDonatorsAsync() {
            return base.Channel.ListaDonatorsAsync();
        }
        
        public System.Xml.XmlElement AddDonator(
                    string number, 
                    string sexo, 
                    string firstName, 
                    string lastName, 
                    string streetAddress, 
                    string city, 
                    string statefull, 
                    string zipCode, 
                    string eMail, 
                    string userName, 
                    string password, 
                    string telephoneNumber, 
                    string mothersMaiden, 
                    string birthDay, 
                    string age, 
                    string occupation, 
                    string company, 
                    string vehicle, 
                    string bloodType, 
                    string kilograms, 
                    string centimeters, 
                    string guid, 
                    string latitude, 
                    string longitude, 
                    object[] doc) {
            return base.Channel.AddDonator(number, sexo, firstName, lastName, streetAddress, city, statefull, zipCode, eMail, userName, password, telephoneNumber, mothersMaiden, birthDay, age, occupation, company, vehicle, bloodType, kilograms, centimeters, guid, latitude, longitude, doc);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlElement> AddDonatorAsync(
                    string number, 
                    string sexo, 
                    string firstName, 
                    string lastName, 
                    string streetAddress, 
                    string city, 
                    string statefull, 
                    string zipCode, 
                    string eMail, 
                    string userName, 
                    string password, 
                    string telephoneNumber, 
                    string mothersMaiden, 
                    string birthDay, 
                    string age, 
                    string occupation, 
                    string company, 
                    string vehicle, 
                    string bloodType, 
                    string kilograms, 
                    string centimeters, 
                    string guid, 
                    string latitude, 
                    string longitude, 
                    object[] doc) {
            return base.Channel.AddDonatorAsync(number, sexo, firstName, lastName, streetAddress, city, statefull, zipCode, eMail, userName, password, telephoneNumber, mothersMaiden, birthDay, age, occupation, company, vehicle, bloodType, kilograms, centimeters, guid, latitude, longitude, doc);
        }
        
        public bool ExportarXML(int[] posicao, string caminhoGuardar) {
            return base.Channel.ExportarXML(posicao, caminhoGuardar);
        }
        
        public System.Threading.Tasks.Task<bool> ExportarXMLAsync(int[] posicao, string caminhoGuardar) {
            return base.Channel.ExportarXMLAsync(posicao, caminhoGuardar);
        }
        
        public bool ExportJSON(int[] posicao, string path) {
            return base.Channel.ExportJSON(posicao, path);
        }
        
        public System.Threading.Tasks.Task<bool> ExportJSONAsync(int[] posicao, string path) {
            return base.Channel.ExportJSONAsync(posicao, path);
        }
        
        public void SendEmails(string email, string bloodtype) {
            base.Channel.SendEmails(email, bloodtype);
        }
        
        public System.Threading.Tasks.Task SendEmailsAsync(string email, string bloodtype) {
            return base.Channel.SendEmailsAsync(email, bloodtype);
        }
        
        public Interface.ServiceReference1.NetworkCredential Credentials() {
            return base.Channel.Credentials();
        }
        
        public System.Threading.Tasks.Task<Interface.ServiceReference1.NetworkCredential> CredentialsAsync() {
            return base.Channel.CredentialsAsync();
        }
    }
}
